### ISSUE TITLE
Please add support for SchemaLess data to Sink classes

### ISSUE THREAD

**Issue by dbtucker** [kineticadb/kinetica-connector-kafka#1]
A best practice for Sink Connectors is to support SinkRecords without schema if a reasonable mapping can be performed based on the raw data structure (CSV or JSON record, for example).   There are example of this in the DynamoDB and JDBC Sink connectors

Until schema-less SinkRecords are supported, the README.md file should be updated to require the value.converter.schemas.enable flag be set to "true" when using the connector.

**Comment by dkatz** [comment]
I've added the value.converter.schemas.enable flag be set to "true" information to the README.md file.
